FROM node:lts-buster-slim

RUN npm config set registry https://registry.npm.taobao.org/ \
    && npm install web3 yamljs \
    && npm cache clean

WORKDIR /home
COPY .. .

CMD [ "node", "ReceiveETH_test.js" ]