FROM node:lts-buster-slim

RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list \
    && apt update \
    && apt install build-essential python -y \
    && apt autoremove -y \
    && apt clean \
    && npm config set registry https://registry.npm.taobao.org/ \
    && npm install web3 yamljs \
    && npm cache clean --force

EXPOSE 7545

COPY . /home
WORKDIR /home/client

CMD [ "node", "ReceiveETH_test.js" ]